name: Compilation test

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} Run Compilation

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 53c8c8d6d0b957e9d4ae02f99d5993d5e699d522
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Compile Java sources
      run: |
        PROJECT_DIRS=$(find . -maxdepth 2 -type f -name 'pom.xml' -exec dirname {} \;)
        for PROJECT_DIR in $PROJECT_DIRS; do
          echo "Compiling project in directory: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          mvn clean install -Dmaven.test.skip=true
          cd -
        done
